<?php

/**
 * Created by IntelliJ IDEA.
 * User: maxsky
 * Date: 2021/6/4
 * Time: 17:00
 */

namespace BaiduAipTests\TestLib;

use BaiduAipTests\TestCase;

class HttpTest extends TestCase {

    private $aipBase;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->aipBase = new ExtendAipBase('', '', '');
    }

    public function testVersion() {
        $this->assertSame('2_2_20', $this->aipBase->getVersion());
    }
}
