<?php

/**
 * Created by IntelliJ IDEA.
 * User: maxsky
 * Date: 2021/6/4
 * Time: 17:00
 */

class HttpTest extends TestCase {

    private $aipBase;

    protected function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->aipBase = new ExtendAipBase('', '', '');
    }

    public function testVersion() {
        $this->assertSame($this->aipBase->getVersion(), '2_2_20');
    }
}
